# profiles/slurm_profile/config.yaml

jobs: 6
use-conda: true
conda-frontend: conda
use-singularity: true
singularity-args: "--nv -B /ifs/data/research/unique"
cluster-config: "configs/cluster-config.yaml"
configfile: "configs/config.yaml"
cluster: "sbatch --partition={cluster.partition} {cluster.gres} --mem={cluster.mem} --cpus-per-task={cluster.cpus} --time={cluster.time} --output {cluster.output} --error {cluster.error}"
rerun-incomplete: true
latency-wait: 60

