# profiles/brando_profile/config.yaml

executor: slurm
jobs: 8

use-conda: true
conda-frontend: conda

use-singularity: true
singularity-args: "-B /ifs/data/research/unique"

configfile: "configs/config.yaml"

rerun-incomplete: true
latency-wait: 60


# Defaults resourses for all rules
default-resources:
  slurm_partition: "research"
  mem: "24G"         # plugin accepts mem (string with unit) or mem_mb (int)
  runtime: 5000       # minutes
  threads: 24


# Rule-specific resources 
set-resources:
  basecalling:
    slurm_partition: "gpu"
    gpu: 3           # replaces old gres="--gres=gpu:3"
    mem: "64G"
    runtime: 11520   # 8 days in minutes

  create_log:
    slurm_partition: "research"
    mem: "2G"
    runtime: 5       # 00:05:00

  QC_NanoP_unaligned:
    slurm_partition: "research"
    mem: "24G"
    runtime: 120     # 02:00:00

  ubam_to_fastq:
    slurm_partition: "research"
    mem: "24G"
    runtime: 180     # 03:00:00

  filter_fastq:
    slurm_partition: "research"
    mem: "24G"
    runtime: 180     # 03:00:00

  alignment:
    slurm_partition: "research"
    mem: "32G"       # was 32G
    runtime: 1200    # 20:00:00

  QC_fastq_pre_filtering:
    slurm_partition: "research"
    mem: "24G"
    runtime: 720     # 12:00:00

  QC_fastq_post_filtering:
    slurm_partition: "research"
    mem: "24G"
    runtime: 720        # 12:00:00

  variant_calling_snps_indels:
    slurm_partition: "research"
    mem: "96G"
    runtime: 1200       # 20:00:00

  variant_calling_sv:
    slurm_partition: "research"
    mem: "32G"
    runtime: 120        # 02:00:00

  longphase_modcall:
    slurm_partition: "research"
    mem: "64G"          # 64G
    runtime: 600        # 10:00:00

  longphase_phase:
    slurm_partition: "research"
    mem: "200G"
    runtime: 600        # 10:00:00

  longphase_haplotag:
    slurm_partition: "research"
    mem: "24G"
    runtime: 600        # 10:00:00

  QC_phased_bam:
    slurm_partition: "research"
    mem: "24G"
    runtime: 720        # 12:00:00

  sex_from_camino:
    slurm_partition: "research"
    mem: "16G"
    runtime: 150        

  methylation_calling:
    slurm_partition: "research"
    mem: "64G"
    runtime: 900        # 15:00:00

  TE_calling:
    slurm_partition: "research"
    mem: "128G"
    runtime: 720        # 12:00:00

  TR_calling:
    slurm_partition: "research"
    mem: "28G"
    runtime: 1440        # 24:00:00

  TR_methylation_calling:
    slurm_partition: "research"
    mem: "28G"
    runtime: 600        # 10:00:00

  non_ref_TE_methylation_calling:
    slurm_partition: "research"
    mem: "24G"
    runtime: 180        # 03:00:00

  ref_TE_methylation_calling_cpg_res:
    slurm_partition: "research"
    mem: "32G"
    runtime: 360        # 06:00:00

  ref_TE_methylation_calling_averages:
    slurm_partition: "research"
    mem: "32G"
    runtime: 1440       # 24:00:00


set-threads:
  basecalling: 8
  create_log: 2
  QC_NanoP_unaligned: 32
  ubam_to_fastq: 32
  filter_fastq: 32
  alignment: 16
  QC_fastq_pre_filtering: 24
  QC_fastq_post_filtering: 24
  variant_calling_snps_indels: 48
  variant_calling_sv: 16
  longphase_modcall: 16
  longphase_phase: 32
  longphase_haplotag: 48
  QC_phased_bam: 24
  sex_from_camino: 8
  methylation_calling: 16
  TE_calling: 48
  TR_calling: 16
  TR_methylation_calling: 8
  non_ref_TE_methylation_calling: 16
  ref_TE_methylation_calling_cpg_res: 32
  ref_TE_methylation_calling_averages: 16
