#!/bin/bash
# -----------------------------------------------------------------------------
# Script Name:    TLDR-methylation_v2.sh
# Description:    This script has the primary function of typing DNA methylation (DNAm)
#                 in non reference Transposable Elements (TE). It uses as input the 
#                 output of the tool TLDR. The script first tidy the output directory
#                 of the TLDR tool, removing files not used. Then, the non reference
#                 TE with a PASS label are kept and haplotype-specific DNAm at cpg sited 
#                 and average of the TE, upstream and downstream regions are calculated.
# Author:         Leena Putzeys, Brando Poggiali
# Date Created:   2025-03-02
# Last Modified:  2025-07-08
# Version:        2.0.0
# License:        MIT
# Dependencies:   [modkit, bgzip, tabix, samtools, awk]
# -----------------------------------------------------------------------------



# Print usage instructions 
usage() {
    echo "Usage: $0 -i <tldr_out> -o <output_dir> -s <sample_id> -f <flanking_bases> -t <threads>"
    echo "  -i <tldr_out>       Output generated by TLDR"
    echo "  -o <output_dir>       Output directory"
    echo "  -s <sample_id>        SampleID to be used in file names"
    echo "  -f <flanking_bases>   Number of flanking bases to include (default: 250)"
    echo "  -t <threads>   Number of threads (default: 8)"
    exit 1
}

# Check required tools
REQUIRED_TOOLS=("modkit" "bgzip" "tabix" "awk" "samtools")

for tool in "${REQUIRED_TOOLS[@]}"; do
    if ! command -v "$tool" &>/dev/null; then
        echo "Error: Required tool '$tool' is not installed or not in PATH."
        exit 1
    fi
done


# Defaults
FLANKING_BASES=250
THREADS=8

# Parse command-line arguments
while getopts "i:o:s:f:t:" opt; do
    case $opt in
        i) TLDR_IN="$OPTARG" ;;
        o) OUTPUT_DIR="$OPTARG" ;;
        s) SAMPLE_ID="$OPTARG" ;;
        f) FLANKING_BASES="$OPTARG" ;;
        t) THREADS="$OPTARG" ;;
        *) usage ;;
    esac
done

THREADS_MODKIT=$(( THREADS / 16 ))

# Check required arguments
if [[ -z "$TLDR_IN" || -z "$OUTPUT_DIR"  || -z "$SAMPLE_ID" ]]; then
    usage
fi

# --- File and directory paths ---
# TLDR_PASS="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.txt"
TLDR_SUMMARY="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.txt"
METH_SUMMARY_PHASED="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.meth.phased.txt"
METH_SUMMARY_UNPHASED="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.meth.unphased.txt"
TLDR_OUTPUT_PATH=$(dirname "$TLDR_IN")
detailed_dir="${TLDR_OUTPUT_PATH}/${SAMPLE_ID}"
outbase="${OUTPUT_DIR}/modkit"
failed_file_list="${TLDR_OUTPUT_PATH}/${SAMPLE_ID}/list_of_failed_files.txt"


# Function declarations
extract_methylation_stats() {
    local file=$1
    local var_prefix=$2

    if [[ -f "$file" && -s "$file" ]]; then
        local percent=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$file")
        local count=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$file")
        eval "${var_prefix}_percent_m=\"$percent\""
        eval "${var_prefix}_count_valid_m=\"$count\""
    fi
}
#---------------------STEP 1: FILTERING--------------------------
#Filter non reference TE which has PASS label 
echo ""
echo "STEP 1: Filter TLDR output: PASS only"
echo " "

uuid_file=$(mktemp)

awk -F'\t' -v summary="$TLDR_SUMMARY" \
             -v empty="$METH_SUMMARY_PHASED" \
             -v uuid_out="$uuid_file" '
BEGIN {
    OFS = "\t"
    summary_found = 0
}
NR == 1 {
    # Dynamically create the summary file header using actual input
    print $1, $2, $3, $4, $5, $6 ":" $7, $10, $23, $24 > summary
    next
}
$26 == "PASS" {
    # Write filtered row to summary (selected columns)
    print $1, $2, $3, $4, $5, $6 ":" $7, $10, $23, $24 >> summary
    # Write UUID (column 1) to a temp file
    print $1 >> uuid_out
    summary_found = 1
}
END {
    # If no PASS rows were found, touch an empty summary to prevent errors downstream
    if (!summary_found) {
        print "File has only one line — exiting gracefully."
        system("touch \"" empty "\"")
        exit 0
    }
}' "$TLDR_IN"


# Ensure the summary file exists
if [[ ! -f "$TLDR_SUMMARY" ]]; then
    echo "Error: Summary file $TLDR_SUMMARY does not exist."
    exit 1
fi


# Initialize the methylation summary files as a copy of TLDR_SUMMARY.
echo -e "$(head -n 1 "$TLDR_SUMMARY")\tTEAverageMeth\tTE_Nvalid\tUpstream_AverageMeth\tUpstream_Nvalid\tDownstream_AverageMeth\tDownstream_Nvalid" > "$METH_SUMMARY_PHASED"
cp "$METH_SUMMARY_PHASED" "$METH_SUMMARY_UNPHASED"

#----------------------STEP 2: MOVE FAILED FILES-------------------
# Move failed TE call files in failed directory which will be delete
# We initially kept these files, then we decided to eliminate them.
echo ""
echo "STEP 2: Move failed TE calls in failed directory"
echo ""

faileddir="${detailed_dir}/failed_UUIDs"
mkdir -p "$faileddir"

echo "Indexing UUIDs into memory..."

#1: Load UUIDs into associative array
#declare -A uuid_map
#while read -r uuid; do
#    [[ -n "$uuid" ]] && uuid_map["$uuid"]=1
#done < "$uuid_file"

#2: Create a temp file for files to move and a file to store failed uuid files

if [ ! -f "$failed_file_list" ]; then
    touch "$failed_file_list"
fi

move_list=$(mktemp)

echo "Scanning files to move..."

# Step 3: Find all files and compare against UUIDs
MAX_JOBS=$((THREADS))  # Safe default
job_count=0
echo "Max job: $MAX_JOBS"

check_failed_file() {
    local file="$1"
    local filename=$(basename "$file")
    # 1. Skip if in failed_file_list
    if [[ -n "${failed_file_list:-}" && -f "$failed_file_list" ]]; then
        grep -Fxqm1 -- "$file" "$failed_file_list" && return 0
    fi 
    # 2. Skip if in failed directory
    [[ -n "${faileddir:-}" && "$file" == "$faileddir"* ]] && return 0
    
    # 3. UUID matching (Is any line in uuid_file present in filename?)
    if [[ -f "$uuid_file" ]] && grep -Ff "$uuid_file" <<< "$filename" | grep -q .; then
        return 0
    fi
    
    # 4. Success - Add to list
    echo "$file"
}

export uuid_file failed_file_list faileddir
export -f check_failed_file

find "$detailed_dir" -type f -print0 \
  | parallel -0 -j "$MAX_JOBS" check_failed_file {} \
  > "$move_list"


echo "Finished while loop"

echo "Moving $(wc -l < "$move_list") unmatched files to $faileddir using $parallel_jobs parallel jobs..."

# Step 4: Move files in parallel
parallel_jobs=$(nproc)
cat "$move_list" | xargs -I{} -P "$parallel_jobs" mv {} "$faileddir/"

# Clean up
cat "$move_list" >> "$failed_file_list"
#rm "$move_list"

echo "✅ Done."

#-------------------STEP 3: METHYLATION ANALYSIS--------------------
# Calculate methylation values for retained TE insertions
echo "" 
echo "STEP 3: Executing modkit for passed samples in $detailed_dir..."
echo ""

mkdir -p "$outbase"

echo "Files found:"
find "$detailed_dir" -type f -name "*.te.bam" | wc -l
echo

process_uuid_file() {
    file="$1"

    echo "Processing file $count: $file"
    echo

    # Ensure the file is not inside failed UUIDs
    if [[ "$file" == "$faileddir"* ]]; then 
        echo "Skipping. Detected in failed directory: $file"
        return
    fi

    # Extract UUID from the filename (everything between the last `.` and `.te.bam`)
    filename=$(basename "$file")
    tmp="${filename#*.}"
    uuid="${tmp%%.*}"
    if [[ -z "$uuid" ]]; then
        echo "Warning: Could not extract UUID from $filename"
        return
    fi

    # Locate associated files
    cons_ref="${detailed_dir}/${uuid}.cons.ref.fa"
    cons_ref_fai="${cons_ref}.fai"
    details_out="${detailed_dir}/${uuid}.details.out"
    te_bed=$(find "$detailed_dir" -type f -name "*.${uuid}.bed" | head -n 1)  # Match files with anything before UUID
    te_bam="${detailed_dir}/${filename}"  # Keep original filename
    te_bam_bai="${te_bam}.bai"  # Index file 

    # Check for missing BED entry that can cause script to break
    if [[ ! -f "$te_bed" ]]; then
        echo "WARNING: Missing te_bed for UUID $uuid. Skipping modkit and adding NA values to summary."
        missing_values=".\t.\t.\t.\t.\t."
        
        # Extract the matching line from TLDR_SUMMARY and append the missing columns
        matching_line=$(awk -v uuid="$uuid" '$1 == uuid' "$TLDR_SUMMARY")
        
        if [[ -n "$matching_line" ]]; then
            echo -e "${matching_line}\t${missing_values}" > "${METH_SUMMARY_PHASED}.${uuid}.tmp"
            echo -e "${matching_line}\t${missing_values}" > "${METH_SUMMARY_UNPHASED}.${uuid}.tmp"
        fi
        return
    fi	    

    # Create a new BED file without the strand column
    modified_te_bed="${outbase}/${uuid}_te_modified.bed"
    awk '{OFS="\t"} {print $1, $2, $3}' "$te_bed" > "$modified_te_bed"

    # Create an upstream-shifted BED file (#FLANKING_BASES bp from startm 250 bp default)
    te_bed_upstream="${outbase}/${uuid}_upstream.bed"
    awk -v flank="$FLANKING_BASES" '{OFS="\t"} {start=$2-flank; if (start < 0) start=0; print $1, start, $2}' "$modified_te_bed" > "$te_bed_upstream"

    # Create an downstream-shifted BED file (#FLANKING_BASES bp from startm 250 bp default)
    te_bed_downstream="${outbase}/${uuid}_downstream.bed"
    awk -v flank="$FLANKING_BASES" '{OFS="\t"} {print $1, $3, $3+flank}' "$modified_te_bed" > "$te_bed_downstream"
    
    #Print uuid info 
    echo "=====processing UUID: $uuid ======="
    echo "cons_ref: $cons_ref"
    echo "cons_ref_fai: $cons_ref_fai"
    echo "te_bed: $te_bed"
    echo "te_bam: $te_bam"
    echo "te_bam_bai: $te_bam_bai"

    # Ensure all necessary files exist
    if [[ -f "$cons_ref" && -f "$cons_ref_fai" && -f "$modified_te_bed" && -f "$te_bed_upstream" && -f "$te_bed_downstream" && -f "$te_bam" && -f "$te_bam_bai" ]]; then

        echo "Start modkit processing of $uuid" 
 
        # Modkit analysis
        modkit pileup -t "$THREADS_MODKIT" --ref "$cons_ref" --cpg "$te_bam" --combine-strands --prefix "pileup_$uuid" --partition-tag HP --ignore h --mod-threshold m:0.8 "$outbase" 2>/dev/null 
        modkit pileup -t "$THREADS_MODKIT" --ref "$cons_ref" --cpg "$te_bam" --combine-strands --ignore h --mod-threshold m:0.8 "${outbase}/pileup_${uuid}_unphased.bed" 2>/dev/null 

        for bed in 1 2; do
            bedfile="$outbase/pileup_${uuid}_${bed}.bed" 
            [[ -f "$bedfile" && -s "$bedfile" ]] || continue
            bgzip "$bedfile" && tabix "$bedfile.gz"
        done 

        bgzip "$outbase/pileup_${uuid}_unphased.bed"
        tabix "$outbase/pileup_${uuid}_unphased.bed.gz"

        modkit stats -t "$THREADS_MODKIT" --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null 
        modkit stats -t "$THREADS_MODKIT" --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null 
	modkit stats -t "$THREADS_MODKIT" --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_ungrouped.tsv" "${outbase}/pileup_${uuid}_ungrouped.bed.gz" 2>/dev/null 
        modkit stats -t "$THREADS_MODKIT" --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null 
	modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null 
        modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null 
	modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null 
        modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null 
	modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null 
        modkit stats -t "$THREADS_MODKIT" --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null 
	
        stats_TE_1="${outbase}/${uuid}_TE_stats_1.tsv"
        stats_TE_2="${outbase}/${uuid}_TE_stats_2.tsv"
        stats_TE_unphased="${outbase}/${uuid}_TE_stats_unphased.tsv"
        stats_upTE_1="${outbase}/${uuid}_upstreamTE_stats_1.tsv"
        stats_upTE_2="${outbase}/${uuid}_upstreamTE_stats_2.tsv"
        stats_upTE_unphased="${outbase}/${uuid}_upstreamTE_stats_unphased.tsv"
        stats_downTE_1="${outbase}/${uuid}_downstreamTE_stats_1.tsv"
        stats_downTE_2="${outbase}/${uuid}_downstreamTE_stats_2.tsv"
        stats_downTE_unphased="${outbase}/${uuid}_downstreamTE_stats_unphased.tsv"

        # Initialize values as missing
        hp1_TE_percent_m="."
        hp1_TE_count_valid_m="."
        hp1_upTE_percent_m="."
        hp1_upTE_count_valid_m="."
        hp1_downTE_percent_m="."
        hp1_downTE_count_valid_m="."
        hp2_TE_percent_m="."
        hp2_TE_count_valid_m="."
        hp2_upTE_percent_m="."
        hp2_upTE_count_valid_m="."
        hp2_downTE_percent_m="."
        hp2_downTE_count_valid_m="."
        unphased_TE_percent_m="."
        unphased_TE_count_valid_m="."
        unphased_upTE_percent_m="."
        unphased_upTE_count_valid_m="."
        unphased_downTE_percent_m="."
        unphased_downTE_count_valid_m="."

        # Extract the Phasing column
        phasing_info=$(awk -v uuid="$uuid" '$1 == uuid {print $9}' "$TLDR_SUMMARY")

        # Determine whether each haplotype exists
        hp1_exists=false
        hp2_exists=false
	
	if echo "$phasing_info" | grep -qE ":1:"; then
	    hp1_exists=true
	else
	    hp1_TE_percent_m="."
	    hp1_TE_count_valid_m="."
	fi

        if echo "$phasing_info" | grep -qE ":2:"; then
            hp2_exists=true
        else
            hp2_TE_percent_m="."
            hp2_TE_count_valid_m="."
        fi

        # Only extract TE region values if haplotype exists
        [[ "$hp1_exists" == true ]] && extract_methylation_stats "$stats_TE_1" "hp1_TE"
        [[ "$hp2_exists" == true ]] && extract_methylation_stats "$stats_TE_2" "hp2_TE"
        
        # Always try to extract upstream/downstream regardless of phasing
        extract_methylation_stats "$stats_upTE_1"       "hp1_upTE"
        extract_methylation_stats "$stats_downTE_1"     "hp1_downTE"
        extract_methylation_stats "$stats_upTE_2"       "hp2_upTE"
        extract_methylation_stats "$stats_downTE_2"     "hp2_downTE"
        
        # Unphased values (always attempt to extract)
        extract_methylation_stats "$stats_TE_unphased"        "unphased_TE"
        extract_methylation_stats "$stats_upTE_unphased"      "unphased_upTE"
        extract_methylation_stats "$stats_downTE_unphased"    "unphased_downTE"


        # Format the extracted values
        TAB=$'\t'
        meth_TE_values="${hp1_TE_percent_m},${hp2_TE_percent_m}"
        meth_TE_counts="${hp1_TE_count_valid_m},${hp2_TE_count_valid_m}"
        meth_upTE_values="${hp1_upTE_percent_m},${hp2_upTE_percent_m}"
        meth_upTE_counts="${hp1_upTE_count_valid_m},${hp2_upTE_count_valid_m}"
        meth_downTE_values="${hp1_downTE_percent_m},${hp2_downTE_percent_m}"
        meth_downTE_counts="${hp1_downTE_count_valid_m},${hp2_downTE_count_valid_m}"
        meth_values_phased="${meth_TE_values}${TAB}${meth_TE_counts}${TAB}${meth_upTE_values}${TAB}${meth_upTE_counts}${TAB}${meth_downTE_values}${TAB}${meth_downTE_counts}"
        meth_values_unphased="${unphased_TE_percent_m}${TAB}${unphased_TE_count_valid_m}${TAB}${unphased_upTE_percent_m}${TAB}${unphased_upTE_count_valid_m}${TAB}${unphased_downTE_percent_m}${TAB}${unphased_downTE_count_valid_m}"

        # Print results for phased and unphased in a tmp file
        if [[ -n "$meth_values_phased" ]]; then
            if grep -q "^$uuid" "$TLDR_SUMMARY"; then
                awk -v uuid="$uuid" -v values="$meth_values_phased" '
                BEGIN {OFS="\t"} 
                {
                  gsub(/^ +| +$/, "", $1)
                }
                $1 == uuid {print $0, values}
                ' "$TLDR_SUMMARY" > "${METH_SUMMARY_PHASED}.${uuid}.tmp"
            
            else 
                echo "Warning: UUID $uuid not found in ${TLDR_SUMMARY}. Skipping." 
            fi
        else
            echo "Skipping update for UUID: $uuid (no valid methylation data found)"
        fi

        if [[ -n "$meth_values_unphased" ]]; then
            if grep -q "^$uuid" "$TLDR_SUMMARY"; then
                awk -v uuid="$uuid" -v values="$meth_values_unphased" '
                BEGIN {OFS="\t"} 
                {
                  gsub(/^ +| +$/, "", $1)
                }
                $1 == uuid {print $0, values}
                ' "$TLDR_SUMMARY" > "${METH_SUMMARY_UNPHASED}.${uuid}.tmp"
       
            else 
                echo "Warning: UUID $uuid not found in ${METH_SUMMARY_UNPHASED}. Skipping." 
            fi
        else
            echo "Skipping update for UUID: $uuid (no valid methylation data found)"
        fi
    echo "Done with: $file"
    echo 
    
    else
        echo "WARNING: missing files required for UUID: $uuid. Skipping."
        continue 
    fi
}


MAX_JOBS=$((THREADS))  # or you can divide it for another safe value, e.g., 4 or 8
count=0
job_count=0
# Launch parallel processing of uuid in backgrounds
for file in $(find "$detailed_dir" -type f -name "*.te.bam"); do
    ((count++))

    process_uuid_file "$file" &
    ((job_count++))

    if (( job_count >= MAX_JOBS )); then
        wait  # Wait for all background jobs to finish before launching more
        job_count=0
    fi
done

wait  # Final wait to ensure all jobs finish

# Append all uuid summary meth files in the final files and sort uuids based on chr and position
# Merge phased and unphased temp files in background
(
  cat ${METH_SUMMARY_UNPHASED}.*.tmp >> "${METH_SUMMARY_UNPHASED}"
  rm ${METH_SUMMARY_UNPHASED}.*.tmp
) &

(
  cat ${METH_SUMMARY_PHASED}.*.tmp >> "${METH_SUMMARY_PHASED}"
  rm ${METH_SUMMARY_PHASED}.*.tmp
) &

# Wait for merging to finish before sorting
wait

# Now sort both files in parallel
(
  head -n 1 "${METH_SUMMARY_PHASED}" > "${METH_SUMMARY_PHASED}.tmp"
  tail -n +2 "${METH_SUMMARY_PHASED}" | sort -k2,2V -k3,3n >> "${METH_SUMMARY_PHASED}.tmp"
  mv "${METH_SUMMARY_PHASED}.tmp" "${METH_SUMMARY_PHASED}"
) &

(
  head -n 1 "${METH_SUMMARY_UNPHASED}" > "${METH_SUMMARY_UNPHASED}.tmp"
  tail -n +2 "${METH_SUMMARY_UNPHASED}" | sort -k2,2V -k3,3n >> "${METH_SUMMARY_UNPHASED}.tmp"
  mv "${METH_SUMMARY_UNPHASED}.tmp" "${METH_SUMMARY_UNPHASED}"
) &

# Wait for both sorts to finish
wait

# Remove temporary files 
#rm "$uuid_file"

rm ${outbase}/*.tsv &
rm ${outbase}/*_te_modified.bed &
rm ${outbase}/*_upstream.bed &
rm ${outbase}/*_downstream.bed &
#rm  -rf "$faileddir" &

wait
#Merge bed files containing all cpg DNAm levels in one single bed files for hap1, hap2, ungrouped, and unphased
(zcat ${outbase}/pileup_*_1.bed.gz > ${outbase}/all_uuids_pileup_haplotype_1.bed && rm ${outbase}/pileup_*_1.bed.gz*) &
(zcat ${outbase}/pileup_*_2.bed.gz > ${outbase}/all_uuids_pileup_haplotype_2.bed && rm ${outbase}/pileup_*_2.bed.gz*) &
(cat ${outbase}/pileup_*_ungrouped.bed > ${outbase}/all_uuids_pileup_ungrouped.bed && rm ${outbase}/pileup_*_ungrouped.bed) &
(zcat ${outbase}/pileup_*_unphased.bed.gz > ${outbase}/all_uuids_pileup_unphased.bed && rm ${outbase}/pileup_*_unphased.bed.gz*) &

wait

echo "Processing complete. Phased summary saved at: $METH_SUMMARY_PHASED, unphased summary saved at: $METH_SUMMARY_UNPHASED"

# echo "Temporary methylation files can be found in $outbase"
 
