__default__:
  partition: "research"
  gres: ""
  time: "4-00:00:00"
  mem: "24G"
  cpus: 24 # default 8

basecalling:
  partition: "gpu"
  gres: "--gres=gpu:3"
  time: "8-00:00:00"
  mem: "64G"
  cpus: 8

QC_NanoP_unaligned:
  partition: "research"
  time: "02:00:00"
  mem: "24G"
  cpus: 32

alignment:
  partition: "research"
  time: "10:00:00"
  mem: "132G"
  cpus: 80

coverage_calculation:
  time: "00:45:00"
  partition: "research"
  mem: "32G"
  cpus: 24

QC_LRS_fastq:
  time: "06:00:00"
  partition: "research"
  mem: "32G"
  cpus: 48

QC_LRS_aligned:
  time: "03:00:00"
  partition: "research"
  mem: "64G"
  cpus: 24

QC_NanoP_aligned:
  time: "03:00:00"
  partition: "research"
  mem: "32G"
  cpus: 24

variant_calling_snps_indels:
  time: "06:00:00"
  partition: "research"
  mem: "96G"
  cpus: 48

variant_calling_sv:
  time: "00:45:00"
  partition: "research"
  mem: "32G"
  cpus: 16

phasing:
  partition: "research"
  time: "08:00:00"
  mem: "160G"
  cpus: 32

methylation_calling:
  partition: "research"
  mem: "64G"
  cpus: 16

TE_calling:
  partition: "research"
  time: "04:00:00"
  mem: "128G"
  cpus: 48

TR_calling:
  partition: "research"
  time: "00:45:00"
  mem: "28G"
  cpus: 16

TR_methylation_calling:
  partition: "research"
  time: "00:45:00"
  mem: "28G"
  cpus: 8

non_ref_TE_methylation_calling:
  partition: "research"
  mem: "24G"
  cpus: 16

ref_TE_methylation_calling:
  partition: "research"
  mem: "24G"
  cpus: 16

