__default__:
  partition: "research"
  gres: ""
  time: "4-00:00:00"
  mem: "24G"
  cpus: 24 # default 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error:  "{config[output_dir]}/logs/slurm/{rule}.%j.err"

basecalling:
  partition: "gpu"
  gres: "--gres=gpu:3"
  time: "8-00:00:00"
  mem: "64G"
  cpus: 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_NanoP_unaligned:
  partition: "research"
  time: "02:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

ubam_to_fastq:
  partition: "research"
  time: "03:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

filter_fastq:
  partition: "research"
  time: "03:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

alignment:
  partition: "research"
  time: "20:00:00"
  mem: "132G"
  cpus: 80
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_fastq_pre_filtering:
  partition: "research"
  time: "12:00:00"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_fastq_post_filtering:
  partition: "research"
  time: "12:00:00"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

variant_calling_snps_indels:
  time: "20:00:00"
  partition: "research"
  mem: "96G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

variant_calling_sv:
  partition: "research"
  time: "02:00:00"
  mem: "32G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

longphase_modcall:
  partition: "research"
  time: "10:00:00"
  mem: "64G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

longphase_phase:
  partition: "research"
  time: "10:00:00"
  mem: "200G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"  
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

longphase_haplotag:
  partition: "research"
  time: "10:00:00"
  mem: "64G"
  cpus: 48
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_phased_bam:
  partition: "research"
  time: "12:00:00"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

methylation_calling:
  partition: "research"
  time: "15:00:00"
  mem: "64G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TE_calling:
  partition: "research"
  time: "12:00:00"
  mem: "128G"
  cpus: 48
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_calling:
  partition: "research"
  time: "10:00:00"
  mem: "28G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methyl_call_vcf_prep:
  partition: "research"
  time: "4:00:00"
  mem: "4G"
  cpus: 1
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methyl_call_vcf_chunking:
  partition: "research"
  time: "4:00:00"
  mem: "4G"
  cpus: 1
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methylation_calling:
  partition: "research"
  time: "24:00:00"
  mem: "36G"
  cpus: 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methyl_sort_vcf_chunk:
  partition: "research"
  time: "1:00:00"
  mem: "4G"
  cpus: 1
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methyl_cat_vcfs:
  partition: "research"
  time: "4:00:00"
  mem: "4G"
  cpus: 1
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

non_ref_TE_methylation_calling:
  partition: "research"
  time: "03:00:00"
  mem: "24G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

ref_TE_methylation_calling_cpg_res:
  partition: "research"
  time: "6:00:00"
  mem: "32G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

prep_ref_TE_methylation_calling_averages:
  partition: "research"
  time: "1:00:00"
  mem: "4G"
  cpus: 4
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

modkit_ref_TE_meth_call_phased:
  partition: "research"
  time: "8:00:00"
  mem: "32G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

modkit_ref_TE_meth_call_unphased:
  partition: "research"
  time: "8:00:00"
  mem: "32G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

summarise_ref_TE_methylation_calling_averages:
  partition: "research"
  time: "1:00:00"
  mem: "4G"
  cpus: 1
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

