__default__:
  partition: "research"
  gres: ""
  time: "4-00:00:00"
  mem: "24G"
  cpus: 24 # default 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error:  "{config[output_dir]}/logs/slurm/{rule}.%j.err"

basecalling:
  partition: "gpu"
  gres: "--gres=gpu:3"
  time: "8-00:00:00"
  mem: "64G"
  cpus: 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_NanoP_unaligned:
  partition: "research"
  time: "02:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

ubam_to_fastq:
  partition: "research"
  time: "03:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

filter_fastq:
  partition: "research"
  time: "03:00:00"
  mem: "24G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

alignment:
  partition: "research"
  time: "20:00:00"
  mem: "132G"
  cpus: 80
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_fastq_pre_filtering:
  time: "12:00:00"
  partition: "research"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_fastq_post_filtering:
  time: "12:00:00"
  partition: "research"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"


variant_calling_snps_indels:
  time: "10:00:00"
  partition: "research"
  mem: "96G"
  cpus: 48
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

variant_calling_sv:
  time: "00:45:00"
  partition: "research"
  mem: "32G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

phasing:
  partition: "research"
  time: "20:00:00"
  mem: "200G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

QC_phased_bam:
  time: "12:00:00"
  partition: "research"
  mem: "24G"
  cpus: 24
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

methylation_calling:
  partition: "research"
  mem: "64G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TE_calling:
  partition: "research"
  time: "12:00:00"
  mem: "128G"
  cpus: 48
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_calling:
  partition: "research"
  mem: "28G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

TR_methylation_calling:
  partition: "research"
  mem: "28G"
  cpus: 8
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

non_ref_TE_methylation_calling:
  partition: "research"
  mem: "24G"
  cpus: 16
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

ref_TE_methylation_calling_cpg_res:
  partition: "research"
  mem: "32G"
  cpus: 32
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

ref_TE_methylation_calling_averages:
  partition: "research"
  mem: "32G"
  cpus: 64
  output: "{config[output_dir]}/logs/slurm/{rule}.%j.out"
  error: "{config[output_dir]}/logs/slurm/{rule}.%j.err"

