#!/bin/bash

# Script to analyse non-ref TEs called by TLDR, adding allele-specific methylation information

#set -e 

# Print usage instructions 
usage() {
    echo "Usage: $0 -i <tldr_out> -o <output_dir> -s <sample_id> -f <flanking_bases>"
    echo "  -i <tldr_out>       Output generated by TLDR"
    echo "  -o <output_dir>       Output directory generated by TLDR, where new files will be generated as well"
    echo "  -s <sample_id>        SampleID to be used in file names"
    echo "  -f <flanking_bases>   Number of flanking bases to include (default: 250)"
    exit 1
}

# Check required tools
REQUIRED_TOOLS=("modkit" "bgzip" "tabix" "awk" "samtools")

for tool in "${REQUIRED_TOOLS[@]}"; do
    if ! command -v "$tool" &>/dev/null; then
        echo "Error: Required tool '$tool' is not installed or not in PATH."
        exit 1
    fi
done


# Defaults
FLANKING_BASES=250

# Parse command-line arguments
while getopts "i:o:s:f:" opt; do
    case $opt in
        i) TLDR_IN="$OPTARG" ;;
        o) OUTPUT_DIR="$OPTARG" ;;
        s) SAMPLE_ID="$OPTARG" ;;
        f) FLANKING_BASES="$OPTARG" ;;
        *) usage ;;
    esac
done


# Check required arguments
if [[ -z "$TLDR_IN" || -z "$OUTPUT_DIR"  || -z "$SAMPLE_ID" ]]; then
    usage
fi

# --- File and directory paths ---
TLDR_PASS="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.txt"
TLDR_SUMMARY="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.txt"
METH_SUMMARY_PHASED="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.meth.phased.txt"
METH_SUMMARY_UNPHASED="${OUTPUT_DIR}/${SAMPLE_ID}.table.pass.summary.meth.unphased.txt"
detailed_dir="${OUTPUT_DIR}/${SAMPLE_ID}"
outbase="${OUTPUT_DIR}/modkit"


echo ""
echo "STEP 1: Filter TLDR output: PASS only"
echo " "

# Filter for PASS insertions in TLDR output file
head -n 1 "$TLDR_IN" > "$TLDR_PASS"
grep "PASS" "$TLDR_IN" >> "$TLDR_PASS"

#Check if file does not contain any pass, if this is the case exit the script 
if [ "$(wc -l < "$TLDR_PASS")" -eq 1 ]; then
    echo "File has only one line — exiting gracefully."
    touch "$METH_SUMMARY_PHASED"
    exit 0
fi
# Generate a summary file based on passed output
awk '{OFS="\t"} {print $1, $2, $3, $4, $5, $6":"$7, $10, $22, $23}' "$TLDR_PASS" > "$TLDR_SUMMARY"

# Ensure the summary file exists
if [[ ! -f "$TLDR_SUMMARY" ]]; then
    echo "Error: Summary file $TLDR_SUMMARY does not exist."
    exit 1
fi

# Create a temporary file with all valid UUIDs from the summary
uuid_file=$(mktemp)
awk 'NR>1 {print $1}' "$TLDR_SUMMARY" > "$uuid_file"

# Initialize the methylation summary files as a copy of TLDR_SUMMARY, adding new headers (if it doesn’t exist)
if [[ ! -f "$METH_SUMMARY_PHASED" ]]; then
    echo -e "$(head -n 1 "$TLDR_SUMMARY")\tTEAverageMeth\tTE_Nvalid\tUpstream_AverageMeth\tUpstream_Nvalid\tDownstream_AverageMeth\tDownstream_Nvalid" > "$METH_SUMMARY_PHASED"
    tail -n +2 "$TLDR_SUMMARY" >> "$METH_SUMMARY_PHASED"
    cp "$METH_SUMMARY_PHASED" "$METH_SUMMARY_UNPHASED"
fi

# Move all detail files of entries were not retained in the PASSED summary file. 
faileddir="${detailed_dir}/failed_UUIDs"
mkdir -p "$faileddir"

find "$detailed_dir" -type f -print0 | while IFS= read -r -d '' file; do
    filename=$(basename "$file")

    # Skip files already inside failed_UUID
    if [[ "$file" == "$faileddir"* ]]; then
        continue
    fi

    # Check if the filename contains any UUID from the summary
    if ! grep -Fqf "$uuid_file" <<< "$filename"; then
        echo "No matching UUID in: $filename → Moving to failed_UUIDs"
        mv "$file" "$faileddir/"
    fi
done

# Calculate methylation values for retained TE insertions
echo "" 
echo "STEP 2: Executing modkit for passed samples in $detailed_dir..."
echo ""

find "$detailed_dir" -type f -name "*.te.bam" -print0 | while IFS= read -r -d '' file; do
    set +e
    echo "Processing file: $file"

    # Ensure the file is not inside failed UUIDs
    if [[ "$file" == "$faileddir"* ]]; then 
        echo "Skipping. Detected in failed directory: $file"
        continue
    fi

    # Extract UUID from the filename (everything between the last `.` and `.te.bam`)
    filename=$(basename "$file")
    uuid=$(echo "$filename" | grep -oP '[a-f0-9\-]{36}(?=\.te\.bam)')

    if [[ -z "$uuid" ]]; then
        echo "Warning: Could not extract UUID from $filename"
        continue
    fi

    # Locate associated files
    cons_ref="${detailed_dir}/${uuid}.cons.ref.fa"
    cons_ref_fai="${cons_ref}.fai"
    details_out="${detailed_dir}/${uuid}.details.out"
    te_bed=$(find "$detailed_dir" -type f -name "*.${uuid}.bed" | head -n 1)  # Match files with anything before UUID
    te_bam="${detailed_dir}/${filename}"  # Keep original filename
    te_bam_bai="${te_bam}.bai"  # Index file follows .bai suffix

    mkdir -p "$outbase"

    # Check for missing BED entry that can cause script to break
    if [[ ! -f "$te_bed" ]]; then
        echo "WARNING: Missing te_bed for UUID $uuid. Skipping modkit and adding NA values to summary."
        missing_values=".\t.\t.\t.\t.\t."
        for summary in "$METH_SUMMARY_PHASED" "$METH_SUMMARY_UNPHASED"; do
            grep -q "^$uuid" "$summary" && \
            awk -v uuid="$uuid" -v values="$missing_values" 'BEGIN{OFS="\t"} {gsub(/^ +| +$/, "", $1)} $1 == uuid {print $0, values; next} {print $0}' "$summary" > "${summary}.tmp" && mv "${summary}.tmp" "$summary"
        done
        continue
    fi

    # Create a new BED file without the strand column
    modified_te_bed="${outbase}/${uuid}_te_modified.bed"
    awk '{OFS="\t"} {print $1, $2, $3}' "$te_bed" > "$modified_te_bed"

    # Create an upstream-shifted BED file (#FLANKING_BASES bp from startm 250 bp default)
    te_bed_upstream="${outbase}/${uuid}_upstream.bed"
    awk -v flank="$FLANKING_BASES" '{OFS="\t"} {start=$2-flank; if (start < 0) start=0; print $1, start, $2}' "$modified_te_bed" > "$te_bed_upstream"

    # Create an upstream-shifted BED file (#FLANKING_BASES bp from startm 250 bp default)
    te_bed_downstream="${outbase}/${uuid}_downstream.bed"
    awk -v flank="$FLANKING_BASES" '{OFS="\t"} {print $1, $3, $3+flank}' "$modified_te_bed" > "$te_bed_downstream"

    echo "=====processing UUID: $uuid ======="
    echo "cons_ref: $cons_ref"
    echo "cons_ref_fai: $cons_ref_fai"
    echo "te_bed: $te_bed"
    echo "te_bam: $te_bam"
    echo "te_bam_bai: $te_bam_bai"

    # Ensure all necessary files exist
    if [[ -f "$cons_ref" && -f "$cons_ref_fai" && -f "$modified_te_bed" && -f "$te_bed_upstream" && -f "$te_bed_downstream" && -f "$te_bam" && -f "$te_bam_bai" ]]; then

        echo 
 
        # Modkit analysis
        modkit pileup --ref "$cons_ref" --cpg "$te_bam" --combine-strands --prefix "pileup_$uuid" --partition-tag HP --ignore h --mod-threshold m:0.8 "$outbase" 2>/dev/null
        modkit pileup --ref "$cons_ref" --cpg "$te_bam" --combine-strands --ignore h --mod-threshold m:0.8 "${outbase}/pileup_${uuid}_unphased.bed" 2>/dev/null

        for bed in 1 2; do
            bedfile="$outbase/pileup_${uuid}_${bed}.bed" 
            [[ -f "$bedfile" && -s "$bedfile" ]] || continue
            bgzip "$bedfile" && tabix "$bedfile.gz"
        done 

        bgzip "$outbase/pileup_${uuid}_unphased.bed"
        tabix "$outbase/pileup_${uuid}_unphased.bed.gz"

        modkit stats --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null
        modkit stats --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null
        modkit stats --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_ungrouped.tsv" "${outbase}/pileup_${uuid}_ungrouped.bed.gz" 2>/dev/null
        modkit stats --regions "$modified_te_bed" -c m -o "${outbase}/${uuid}_TE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_upstream" -c m -o "${outbase}/${uuid}_upstreamTE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_1.tsv" "${outbase}/pileup_${uuid}_1.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_2.tsv" "${outbase}/pileup_${uuid}_2.bed.gz" 2>/dev/null
        modkit stats --regions "$te_bed_downstream" -c m -o "${outbase}/${uuid}_downstreamTE_stats_unphased.tsv" "${outbase}/pileup_${uuid}_unphased.bed.gz" 2>/dev/null

        stats_TE_1="${outbase}/${uuid}_TE_stats_1.tsv"
        stats_TE_2="${outbase}/${uuid}_TE_stats_2.tsv"
        stats_TE_unphased="${outbase}/${uuid}_TE_stats_unphased.tsv"
        stats_upTE_1="${outbase}/${uuid}_upstreamTE_stats_1.tsv"
        stats_upTE_2="${outbase}/${uuid}_upstreamTE_stats_2.tsv"
        stats_upTE_unphased="${outbase}/${uuid}_upstreamTE_stats_unphased.tsv"
        stats_downTE_1="${outbase}/${uuid}_downstreamTE_stats_1.tsv"
        stats_downTE_2="${outbase}/${uuid}_downstreamTE_stats_2.tsv"
        stats_downTE_unphased="${outbase}/${uuid}_downstreamTE_stats_unphased.tsv"

        # Initialize values as missing
        hp1_TE_percent_m="."
        hp1_TE_count_valid_m="."
        hp1_upTE_percent_m="."
        hp1_upTE_count_valid_m="."
        hp1_downTE_percent_m="."
        hp1_downTE_count_valid_m="."
        hp2_TE_percent_m="."
        hp2_TE_count_valid_m="."
        hp2_upTE_percent_m="."
        hp2_upTE_count_valid_m="."
        hp2_downTE_percent_m="."
        hp2_downTE_count_valid_m="."
        unphased_TE_percent_m="."
        unphased_TE_count_valid_m="."
        unphased_upTE_percent_m="."
        unphased_upTE_count_valid_m="."
        unphased_downTE_percent_m="."
        unphased_downTE_count_valid_m="."

        # Extract the Phasing column
        phasing_info=$(awk -v uuid="$uuid" '$1 == uuid {print $9}' "$METH_SUMMARY_PHASED")

        # Determine whether each haplotype exists
        hp1_exists=false
        hp2_exists=false
 
        if echo "$phasing_info" | grep -qE ":1:"; then
            hp1_exists=true
        fi

        if echo "$phasing_info" | grep -qE ":2:"; then
            hp2_exists=true
        fi

        # Extract values from HP1 stats only (for TE insertion only if HP1 exists)
        if [[ "$hp1_exists" == true && -f "$stats_TE_1" && -s "$stats_TE_1" ]]; then
            hp1_TE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_TE_1")
            hp1_TE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_TE_1")
        fi

        if [[ -f "$stats_upTE_1" && -s "$stats_upTE_1" ]]; then
            hp1_upTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_upTE_1")
            hp1_upTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_upTE_1")
        fi

        if [[ -f "$stats_downTE_1" && -s "$stats_downTE_1" ]]; then
            hp1_downTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_downTE_1")
            hp1_downTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_downTE_1")
        fi


        # Extract values from HP2 stats (for TE insertion only if HP2 exists)
        if [[ "$hp2_exists" == true && -f "$stats_TE_2" && -s "$stats_TE_2" ]]; then
            hp2_TE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_TE_2")
            hp2_TE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_TE_2")
        fi

        if [[ -f "$stats_upTE_2" && -s "$stats_upTE_2" ]]; then
            hp2_upTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_upTE_2")
            hp2_upTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_upTE_2")
        fi

        if [[ -f "$stats_downTE_2" && -s "$stats_downTE_2" ]]; then
            hp2_downTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_downTE_2")
            hp2_downTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_downTE_2")
        fi

        # Extract values from unphased stats 
        if [[ -f "$stats_TE_unphased" && -s "$stats_TE_unphased" ]]; then
            unphased_TE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_TE_unphased")
            unphased_TE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_TE_unphased")
        fi

        if [[ -f "$stats_upTE_unphased" && -s "$stats_upTE_unphased" ]]; then
            unphased_upTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_upTE_unphased")
            unphased_upTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_upTE_unphased")
        fi

        if [[ -f "$stats_downTE_unphased" && -s "$stats_downTE_unphased" ]]; then
            unphased_downTE_percent_m=$(awk 'NR==2 {print ($8 == "" ? "." : $8)}' "$stats_downTE_unphased")
            unphased_downTE_count_valid_m=$(awk 'NR==2 {print ($7 == "" ? "." : $7)}' "$stats_downTE_unphased")
        fi

        # Force missing values to "."
        if [[ "$hp1_exists" == false ]]; then
            hp1_TE_percent_m="."
            hp1_TE_count_valid_m="."
        fi
        if [[ "$hp2_exists" == false ]]; then
            hp2_TE_percent_m="."
            hp2_TE_count_valid_m="."
        fi

        # Format the extracted values
        TAB=$'\t'
        meth_TE_values="${hp1_TE_percent_m},${hp2_TE_percent_m}"
        meth_TE_counts="${hp1_TE_count_valid_m},${hp2_TE_count_valid_m}"
        meth_upTE_values="${hp1_upTE_percent_m},${hp2_upTE_percent_m}"
        meth_upTE_counts="${hp1_upTE_count_valid_m},${hp2_upTE_count_valid_m}"
        meth_downTE_values="${hp1_downTE_percent_m},${hp2_downTE_percent_m}"
        meth_downTE_counts="${hp1_downTE_count_valid_m},${hp2_downTE_count_valid_m}"
        meth_values_phased="${meth_TE_values}${TAB}${meth_TE_counts}${TAB}${meth_upTE_values}${TAB}${meth_upTE_counts}${TAB}${meth_downTE_values}${TAB}${meth_downTE_counts}"
        meth_values_unphased="${unphased_TE_percent_m}${TAB}${unphased_TE_count_valid_m}${TAB}${unphased_upTE_percent_m}${TAB}${unphased_upTE_count_valid_m}${TAB}${unphased_downTE_percent_m}${TAB}${unphased_downTE_count_valid_m}"

        # Append values to the corresponding line in METH_SUMMARY files

        if [[ -n "$meth_values_phased" ]]; then
            if grep -q "^$uuid" "$METH_SUMMARY_PHASED"; then
                awk -v uuid="$uuid" -v values="$meth_values_phased" 'BEGIN{OFS="\t"}
                {gsub(/^ +| +$/, "", $1)}  # Trim spaces from UUID
                $1 == uuid {print $0, values; next} # If UUID matches, append values
                {print $0}' "$METH_SUMMARY_PHASED" > "${METH_SUMMARY_PHASED}.tmp" && mv "${METH_SUMMARY_PHASED}.tmp" "$METH_SUMMARY_PHASED"
            else 
                echo "Warning: UUID $uuid not found in $METH_SUMMARY_PHASED. Skipping." 
            fi
        else
            echo "Skipping update for UUID: $uuid (no valid methylation data found)"
        fi

        if [[ -n "$meth_values_unphased" ]]; then
            if grep -q "^$uuid" "$METH_SUMMARY_UNPHASED"; then
                awk -v uuid="$uuid" -v values="$meth_values_unphased" 'BEGIN{OFS="\t"}
                {gsub(/^ +| +$/, "", $1)}  # Trim spaces from UUID
                $1 == uuid {print $0, values; next} # If UUID matches, append values
                {print $0}' "$METH_SUMMARY_UNPHASED" > "${METH_SUMMARY_UNPHASED}.tmp" && mv "${METH_SUMMARY_UNPHASED}.tmp" "$METH_SUMMARY_UNPHASED"
            else 
                echo "Warning: UUID $uuid not found in $METH_SUMMARY_UNPHASED. Skipping." 
            fi
        else
            echo "Skipping update for UUID: $uuid (no valid methylation data found)"
        fi
    else
        echo "WARNING: missing files required for UUID: $uuid. Skipping."
        continue
    fi
    set -e
done

rm "$uuid_file"
echo "Processing complete. Phased summary saved at: $METH_SUMMARY_PHASED, unphased summary saved at: $METH_SUMMARY_UNPHASED"
echo "Temporary methylation files can be found in $outbase"
#rm -r $outbase
 
